services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - mongo
    command: "npm run start:prod"
    restart: always  # <-- Automatically restart
    networks:
      - server-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    restart: always  # <-- Automatically restart
    networks:
      - server-network

  mongo-init-replica:
    image: mongo:7
    depends_on:
      - mongo
    restart: "no"  # Keep as is – one-time init job
    entrypoint: >
      bash -c "
      sleep 5 &&
      mongosh --host mongo:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongo:27017\" }]
        })'"
    networks:
      - server-network

volumes:
  mongo_data:

networks:
  server-network:
    driver: bridge
