### Get number of jobs all time
GET http://localhost:4444/api/data-vis/count

### Get number of jobs by year
GET http://localhost:4444/api/data-vis/count?year=2025

### Get number of jobs by year with month
GET http://localhost:4444/api/data-vis/count?yearmonth=2022-02

### Get number of jobs by year, month and status
GET http://localhost:4444/api/data-vis/count?status=ONGOING&yearmonth=2022-02

### Get job count data
GET http://localhost:4444/api/data-vis/count/data

### Get job count data per year
GET http://localhost:4444/api/data-vis/count/data?year=2023

### Get job count data per year with job status
GET http://localhost:4444/api/data-vis/count/data?status=DMD/RELEASED&year=2024





### Get total revenue from jobs all time
GET http://localhost:4444/api/data-vis/revenue

### Get total revenue from jobs by year
GET http://localhost:4444/api/data-vis/revenue?year=2025

### Get total revenue from jobs by month
GET http://localhost:4444/api/data-vis/revenue?yearmonth=2024-03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjlmMmE5NjRkMDFiZGZkOTcyMmM2OSIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTc0MTcxMDcwNiwiZXhwIjoxNzQxNzk3MTA2fQ.pnguRIGsmLXzgjHz6QDOilcoNxUu1A_2SgtJOE9a3xc

### Get array of revenues from jobs by year
GET http://localhost:4444/api/data-vis/revenue/data

### Get array of revenues from jobs by month given by year
GET http://localhost:4444/api/data-vis/revenue/data?year=2024


