### LOGIN USER
POST http://localhost:4444/api/auth/login
content-type: application/json

{
  "email": "user@comtech.com",
  "password": "password123"
}

### LOGIN ADMIN
POST http://localhost:4444/api/auth/login
content-type: application/json

{
  "email": "admin@comtech.com",
  "password": "dashboard2025"
}

### REGISTER USER
POST http://localhost:4444/api/auth/signup
content-type: application/json

{
  "email": "user1@comtech.com",
  "password": "user1"
}