### CONTECH JOM LEGACY API
POST http://localhost:4444/api/legacy
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0YmM2ZTdiYTczNTY5YzNiM2I4YyIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTczMTQyOTg5MiwiZXhwIjoxNzMxNTE2MjkyfQ.dewPl_0YC2cDN1MTpWQLvQqs7JvgR8Dltky6KNJFWw8

{
  "job_id": "JOB-001",
  "tracking_code": "TRACK-005",
  "job_date": "2022-04-01",
  "cus_name": "Mike Brown",
  "cus_address": "901 Maple St",
  "cus_phone": "111-222-3333",
  "work_perf": "Repair",
  "s_charge": 250,
  "s_paymeth": "Cash",
  "s_downpay": 125,
  "s_bal": 125,
  "s_status": "Pending"
}

### GET ALL JOBS
GET http://localhost:4444/api/legacy
?page=
&keyword=jerry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0YmM2ZTdiYTczNTY5YzNiM2I4YyIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTczMTQyOTg5MiwiZXhwIjoxNzMxNTE2MjkyfQ.dewPl_0YC2cDN1MTpWQLvQqs7JvgR8Dltky6KNJFWw8

### GET JOB
GET http://localhost:4444/api/legacy/64ab9c81a4015dde5f41d070
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0YmM2ZTdiYTczNTY5YzNiM2I4YyIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTczMTQyOTg5MiwiZXhwIjoxNzMxNTE2MjkyfQ.dewPl_0YC2cDN1MTpWQLvQqs7JvgR8Dltky6KNJFWw8


### UPDATE JOB
PUT http://localhost:4444/api/legacy/671e3a2dc5f72208de69127c
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0YmM2ZTdiYTczNTY5YzNiM2I4YyIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTczMTQyOTg5MiwiZXhwIjoxNzMxNTE2MjkyfQ.dewPl_0YC2cDN1MTpWQLvQqs7JvgR8Dltky6KNJFWw8

{
  "job_id": "JOB-003 Updatewwww",
  "tracking_code": "TRACK-008"
}

### DELETE JOB
DELETE http://localhost:4444/api/legacy/671e4db1e198adebfde19f87
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0YmM2ZTdiYTczNTY5YzNiM2I4YyIsInJvbGUiOlsidXNlciIsImFkbWluIl0sImlhdCI6MTczMTQyOTg5MiwiZXhwIjoxNzMxNTE2MjkyfQ.dewPl_0YC2cDN1MTpWQLvQqs7JvgR8Dltky6KNJFWw8


### REGISTER USER 
POST http://localhost:4444/api/auth/signup
content-type: application/json

{
  "email": "admin@comtechgingoog.com",
  "password": "dashboard2024"
}

### LOGIN USER
POST http://localhost:4444/api/auth/login
content-type: application/json

{
  "email": "user@comtechgingoog.com",
  "password": "password123"
}

### LOGIN ADMIN
POST http://localhost:4444/api/auth/login
content-type: application/json

{
  "email": "admin@comtechgingoog.com",
  "password": "dashboard2024"
}